language: c
compiler:
- gcc
- clang
sudo: false
addons:
  apt:
    packages:
    - tcl
    - bison
    - flex
    - gcc-multilib
    - texinfo
    - binutils-mingw-w64-i686
    - gcc-mingw-w64-i686
    - g++-mingw-w64-i686
env:
  matrix:
  - OV_ARCH_BITWIDTH=32 DB_COMMANDS=no_dbcommands
  - OV_ARCH_BITWIDTH=64 DB_COMMANDS=dbcommands
  global:
  - TAG="$(git rev-parse --short=10 HEAD)"
  - secure: aV2zLmzVQf8bPo+m4Xiog5DZ0x4iSunLCdEL0Dhm2CqhBA/Hgxz64UC1Y0eit3cRGOyu3QxP3LdV5Dmc+xMk+uIs+dpVc0NZwnIckN+3mrcg0nr6an7ZbZ8nbKf/sRbsviFvqCNNA1zaYaZ1Ub7ljV75MfOY1McJt4D/ymWPeCA=
  - secure: KSiHssC0QJMBpcp4RGl1rgZwEj+QFAFq443g4lpTB28hlcJfVYehA9SvaglBxn684nL6d84wwnzK7jXpwVm85mZQJpj9UcJYji5A/lGrtxow6ytnqhaTOhkbiBf3DNCrzpOVZPT7oIdFYthGTnDbn423MOBia/FOYeG5/cF7QeM=
install: 
script:
- cd ./build
- tclsh ./acplt_build.tcl $DB_COMMANDS $OV_ARCH_BITWIDTH
- cd ..
- mkdir logs
after_success:
- cp ./build/acplt_build.log ./logs/acplt_build-${TRAVIS_JOB_NUMBER}-${TAG}-${CC}-linux${OV_ARCH_BITWIDTH}__OK__.log
- cd ..
- git clone -q --depth=5 -b gh-pages https://acplt-rte-bot:$GITHUB_API_KEY@github.com/acplt/rte-www
- cd ./rte
- if [[ ${TRAVIS_PULL_REQUEST} == "false" && ${CC} == "gcc" ]]; then bash ./tools/travis_createDoc_and_handlerepos.sh ; fi
- cd ..
- bash ./rte/tools/travis_pushAndCloseRepo.sh
after_failure:
- cp ./build/acplt_build.log ./logs/acplt_build-${TRAVIS_JOB_NUMBER}-${TAG}-${CC}-linux${OV_ARCH_BITWIDTH}__FAIL__.log
- cd ..
- git clone -q --depth=5 -b gh-pages https://acplt-rte-bot:$GITHUB_API_KEY@github.com/acplt/rte-www
- cd ./rte
- cd ./build
- tail -n 100 acplt_build.log
- echo "Error lines:"
- cat acplt_build.log | grep error
- cd ../..
- bash ./rte/tools/travis_pushAndCloseRepo.sh

