# @see http://goreleaser.com

project_name: Blueprintz_Composer_for_WordPress
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  -

    binary: blueprintz

    env:
      - CGO_ENABLED=0

    goos:
      - windows
      - darwin
      - linux

    goarch:
      - amd64
#      - 386
#      - arm64
#      - arm

#    goarm:
#      - 5
#      - 6
#      - 7

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
