
/******************************************************************************
*
*   FILE
*   ----
*   getVar.c
*
*   History
*   -------
*   2017-08-30   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_SSChelper
#define OV_COMPILE_LIBRARY_SSChelper
#endif


#include "SSChelper.h"
#include "utilities.h"

#include "libov/ov_macros.h"

OV_DLLFNCEXPORT void SSChelper_getVar_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_SSChelper_getVar pinst = Ov_StaticPtrCast(SSChelper_getVar, pfb);
    OV_INSTPTR_ov_object target=NULL;

    SSChelper_getObjectAndVarnameFromSetVariable(Ov_PtrUpCast(ov_object,pinst),pinst->v_path,&target,&pinst->v_port);

    SSChelper_getNamedVariable(target,pinst->v_port,&pinst->v_var);

    return;
}

