export default {
  Namespace: '',
  GetterTypes: {
    FIND_BY: 'FIND_BY',
    LIST_OPTIONS: 'LIST_OPTIONS',
    LIST_FILTERED_BY: 'LIST_FILTERED_BY',
    LIST_FILTERED: 'LIST_FILTERED'
  },

  ActionTypes: {
    LOAD_ALL: 'LOAD_ALL',
    LOAD_ONE: 'LOAD_ONE',
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    SET_LIST_FILTER: 'SET_LIST_FILTER',
    SET_LIST_FILTER_SORT_BY: 'SET_LIST_FILTER_SORT_BY',
    SET_LIST_FILTER_SORT_ASC: 'SET_LIST_FILTER_SORT_ASC'
  },

  MutationTypes: {
    SET_ALL: 'SET_ALL',
    SET_ONE: 'SET_ONE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    SET_LIST_FILTER: 'SET_LIST_FILTER',
    SET_LIST_FILTER_SORT_BY: 'SET_LIST_FILTER_SORT_BY',
    SET_LIST_FILTER_SORT_ASC: 'SET_LIST_FILTER_SORT_ASC'
  }
}
