# @see http://goreleaser.com

project_name: MqttBroker
env:
  - GO111MODULE=on

before:
  hooks:
    - echo {{ .Version }} > VERSION

builds:
  -
    main: github.com/fhmq/hmq/main.go

    binary: hmq

    env:
      - CGO_ENABLED=0

    goos:
      - windows
      - darwin
      - linux

    goarch:
      - amd64

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  #name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  name_template: "{{ .Tag }}"

release:
  name_template: "{{ .Tag }}"
  draft: true
  prerelease: auto
  github:
      owner: gearboxworks
      name: gearbox

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
