// Code generated by go-bindata.
// sources:
// admin/dist/css/app.78060d66.css
// admin/dist/css/chunk-vendors.19588e8d.css
// admin/dist/css/preferences.11cfcf84.css
// admin/dist/css/projects.6e0ed6ad.css
// admin/dist/css/projectstack.32e9bd3e.css
// admin/dist/favicon.ico
// admin/dist/gears.json
// admin/dist/img/angular.e224f5ed.svg
// admin/dist/img/apache.12c49354.svg
// admin/dist/img/codeigniter.434bf735.svg
// admin/dist/img/django.28fe09a0.svg
// admin/dist/img/drupal.66089b06.svg
// admin/dist/img/elasticsearch.3ecfa530.svg
// admin/dist/img/flask.318d58cb.svg
// admin/dist/img/icons/android-chrome-192x192.png
// admin/dist/img/icons/android-chrome-512x512.png
// admin/dist/img/icons/apple-touch-icon-120x120.png
// admin/dist/img/icons/apple-touch-icon-152x152.png
// admin/dist/img/icons/apple-touch-icon-180x180.png
// admin/dist/img/icons/apple-touch-icon-60x60.png
// admin/dist/img/icons/apple-touch-icon-76x76.png
// admin/dist/img/icons/apple-touch-icon.png
// admin/dist/img/icons/favicon-16x16.png
// admin/dist/img/icons/favicon-32x32.png
// admin/dist/img/icons/msapplication-icon-144x144.png
// admin/dist/img/icons/mstile-150x150.png
// admin/dist/img/icons/safari-pinned-tab.svg
// admin/dist/img/joomla.d8aa2e45.svg
// admin/dist/img/laravel.1766a461.svg
// admin/dist/img/logo.63a7d78d.svg
// admin/dist/img/mariadb.e16110bc.svg
// admin/dist/img/memcached.2bcccabf.svg
// admin/dist/img/mysql.dd2a5a35.svg
// admin/dist/img/nginx.eae76401.svg
// admin/dist/img/nodejs.94cafb0d.svg
// admin/dist/img/perl.a025edb4.svg
// admin/dist/img/php.fa78b345.svg
// admin/dist/img/python.51c2eab2.svg
// admin/dist/img/rails.2db29782.svg
// admin/dist/img/react.9a28da9f.svg
// admin/dist/img/redis.3c39fafe.svg
// admin/dist/img/ruby.514befa7.svg
// admin/dist/img/wordpress.b08e20e3.svg
// admin/dist/index.html
// admin/dist/js/about.a232e5c8.js
// admin/dist/js/about.a232e5c8.js.map
// admin/dist/js/app.dad71b3f.js
// admin/dist/js/app.dad71b3f.js.map
// admin/dist/js/chunk-vendors.2b6afee3.js
// admin/dist/js/chunk-vendors.2b6afee3.js.map
// admin/dist/js/preferences.a0df0240.js
// admin/dist/js/preferences.a0df0240.js.map
// admin/dist/js/projects.9c388682.js
// admin/dist/js/projects.9c388682.js.map
// admin/dist/js/projectstack.3ef56350.js
// admin/dist/js/projectstack.3ef56350.js.map
// admin/dist/manifest.json
// admin/dist/robots.txt
// DO NOT EDIT!

package gearbox

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// adminDistCssApp78060d66Css reads file data from disk. It returns an error on failure.
func adminDistCssApp78060d66Css() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/css/app.78060d66.css")
	name := "admin/dist/css/app.78060d66.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistCssChunkVendors19588e8dCss reads file data from disk. It returns an error on failure.
func adminDistCssChunkVendors19588e8dCss() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/css/chunk-vendors.19588e8d.css")
	name := "admin/dist/css/chunk-vendors.19588e8d.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistCssPreferences11cfcf84Css reads file data from disk. It returns an error on failure.
func adminDistCssPreferences11cfcf84Css() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/css/preferences.11cfcf84.css")
	name := "admin/dist/css/preferences.11cfcf84.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistCssProjects6e0ed6adCss reads file data from disk. It returns an error on failure.
func adminDistCssProjects6e0ed6adCss() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/css/projects.6e0ed6ad.css")
	name := "admin/dist/css/projects.6e0ed6ad.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistCssProjectstack32e9bd3eCss reads file data from disk. It returns an error on failure.
func adminDistCssProjectstack32e9bd3eCss() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/css/projectstack.32e9bd3e.css")
	name := "admin/dist/css/projectstack.32e9bd3e.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistFaviconIco reads file data from disk. It returns an error on failure.
func adminDistFaviconIco() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/favicon.ico")
	name := "admin/dist/favicon.ico"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistGearsJson reads file data from disk. It returns an error on failure.
func adminDistGearsJson() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/gears.json")
	name := "admin/dist/gears.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgAngularE224f5edSvg reads file data from disk. It returns an error on failure.
func adminDistImgAngularE224f5edSvg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/angular.e224f5ed.svg")
	name := "admin/dist/img/angular.e224f5ed.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgApache12c49354Svg reads file data from disk. It returns an error on failure.
func adminDistImgApache12c49354Svg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/apache.12c49354.svg")
	name := "admin/dist/img/apache.12c49354.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgCodeigniter434bf735Svg reads file data from disk. It returns an error on failure.
func adminDistImgCodeigniter434bf735Svg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/codeigniter.434bf735.svg")
	name := "admin/dist/img/codeigniter.434bf735.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgDjango28fe09a0Svg reads file data from disk. It returns an error on failure.
func adminDistImgDjango28fe09a0Svg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/django.28fe09a0.svg")
	name := "admin/dist/img/django.28fe09a0.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgDrupal66089b06Svg reads file data from disk. It returns an error on failure.
func adminDistImgDrupal66089b06Svg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/drupal.66089b06.svg")
	name := "admin/dist/img/drupal.66089b06.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgElasticsearch3ecfa530Svg reads file data from disk. It returns an error on failure.
func adminDistImgElasticsearch3ecfa530Svg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/elasticsearch.3ecfa530.svg")
	name := "admin/dist/img/elasticsearch.3ecfa530.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgFlask318d58cbSvg reads file data from disk. It returns an error on failure.
func adminDistImgFlask318d58cbSvg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/flask.318d58cb.svg")
	name := "admin/dist/img/flask.318d58cb.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgIconsAndroidChrome192x192Png reads file data from disk. It returns an error on failure.
func adminDistImgIconsAndroidChrome192x192Png() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/icons/android-chrome-192x192.png")
	name := "admin/dist/img/icons/android-chrome-192x192.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgIconsAndroidChrome512x512Png reads file data from disk. It returns an error on failure.
func adminDistImgIconsAndroidChrome512x512Png() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/icons/android-chrome-512x512.png")
	name := "admin/dist/img/icons/android-chrome-512x512.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgIconsAppleTouchIcon120x120Png reads file data from disk. It returns an error on failure.
func adminDistImgIconsAppleTouchIcon120x120Png() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/icons/apple-touch-icon-120x120.png")
	name := "admin/dist/img/icons/apple-touch-icon-120x120.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgIconsAppleTouchIcon152x152Png reads file data from disk. It returns an error on failure.
func adminDistImgIconsAppleTouchIcon152x152Png() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/icons/apple-touch-icon-152x152.png")
	name := "admin/dist/img/icons/apple-touch-icon-152x152.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgIconsAppleTouchIcon180x180Png reads file data from disk. It returns an error on failure.
func adminDistImgIconsAppleTouchIcon180x180Png() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/icons/apple-touch-icon-180x180.png")
	name := "admin/dist/img/icons/apple-touch-icon-180x180.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgIconsAppleTouchIcon60x60Png reads file data from disk. It returns an error on failure.
func adminDistImgIconsAppleTouchIcon60x60Png() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/icons/apple-touch-icon-60x60.png")
	name := "admin/dist/img/icons/apple-touch-icon-60x60.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgIconsAppleTouchIcon76x76Png reads file data from disk. It returns an error on failure.
func adminDistImgIconsAppleTouchIcon76x76Png() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/icons/apple-touch-icon-76x76.png")
	name := "admin/dist/img/icons/apple-touch-icon-76x76.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgIconsAppleTouchIconPng reads file data from disk. It returns an error on failure.
func adminDistImgIconsAppleTouchIconPng() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/icons/apple-touch-icon.png")
	name := "admin/dist/img/icons/apple-touch-icon.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgIconsFavicon16x16Png reads file data from disk. It returns an error on failure.
func adminDistImgIconsFavicon16x16Png() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/icons/favicon-16x16.png")
	name := "admin/dist/img/icons/favicon-16x16.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgIconsFavicon32x32Png reads file data from disk. It returns an error on failure.
func adminDistImgIconsFavicon32x32Png() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/icons/favicon-32x32.png")
	name := "admin/dist/img/icons/favicon-32x32.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgIconsMsapplicationIcon144x144Png reads file data from disk. It returns an error on failure.
func adminDistImgIconsMsapplicationIcon144x144Png() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/icons/msapplication-icon-144x144.png")
	name := "admin/dist/img/icons/msapplication-icon-144x144.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgIconsMstile150x150Png reads file data from disk. It returns an error on failure.
func adminDistImgIconsMstile150x150Png() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/icons/mstile-150x150.png")
	name := "admin/dist/img/icons/mstile-150x150.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgIconsSafariPinnedTabSvg reads file data from disk. It returns an error on failure.
func adminDistImgIconsSafariPinnedTabSvg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/icons/safari-pinned-tab.svg")
	name := "admin/dist/img/icons/safari-pinned-tab.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgJoomlaD8aa2e45Svg reads file data from disk. It returns an error on failure.
func adminDistImgJoomlaD8aa2e45Svg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/joomla.d8aa2e45.svg")
	name := "admin/dist/img/joomla.d8aa2e45.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgLaravel1766a461Svg reads file data from disk. It returns an error on failure.
func adminDistImgLaravel1766a461Svg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/laravel.1766a461.svg")
	name := "admin/dist/img/laravel.1766a461.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgLogo63a7d78dSvg reads file data from disk. It returns an error on failure.
func adminDistImgLogo63a7d78dSvg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/logo.63a7d78d.svg")
	name := "admin/dist/img/logo.63a7d78d.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgMariadbE16110bcSvg reads file data from disk. It returns an error on failure.
func adminDistImgMariadbE16110bcSvg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/mariadb.e16110bc.svg")
	name := "admin/dist/img/mariadb.e16110bc.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgMemcached2bcccabfSvg reads file data from disk. It returns an error on failure.
func adminDistImgMemcached2bcccabfSvg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/memcached.2bcccabf.svg")
	name := "admin/dist/img/memcached.2bcccabf.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgMysqlDd2a5a35Svg reads file data from disk. It returns an error on failure.
func adminDistImgMysqlDd2a5a35Svg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/mysql.dd2a5a35.svg")
	name := "admin/dist/img/mysql.dd2a5a35.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgNginxEae76401Svg reads file data from disk. It returns an error on failure.
func adminDistImgNginxEae76401Svg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/nginx.eae76401.svg")
	name := "admin/dist/img/nginx.eae76401.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgNodejs94cafb0dSvg reads file data from disk. It returns an error on failure.
func adminDistImgNodejs94cafb0dSvg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/nodejs.94cafb0d.svg")
	name := "admin/dist/img/nodejs.94cafb0d.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgPerlA025edb4Svg reads file data from disk. It returns an error on failure.
func adminDistImgPerlA025edb4Svg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/perl.a025edb4.svg")
	name := "admin/dist/img/perl.a025edb4.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgPhpFa78b345Svg reads file data from disk. It returns an error on failure.
func adminDistImgPhpFa78b345Svg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/php.fa78b345.svg")
	name := "admin/dist/img/php.fa78b345.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgPython51c2eab2Svg reads file data from disk. It returns an error on failure.
func adminDistImgPython51c2eab2Svg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/python.51c2eab2.svg")
	name := "admin/dist/img/python.51c2eab2.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgRails2db29782Svg reads file data from disk. It returns an error on failure.
func adminDistImgRails2db29782Svg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/rails.2db29782.svg")
	name := "admin/dist/img/rails.2db29782.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgReact9a28da9fSvg reads file data from disk. It returns an error on failure.
func adminDistImgReact9a28da9fSvg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/react.9a28da9f.svg")
	name := "admin/dist/img/react.9a28da9f.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgRedis3c39fafeSvg reads file data from disk. It returns an error on failure.
func adminDistImgRedis3c39fafeSvg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/redis.3c39fafe.svg")
	name := "admin/dist/img/redis.3c39fafe.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgRuby514befa7Svg reads file data from disk. It returns an error on failure.
func adminDistImgRuby514befa7Svg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/ruby.514befa7.svg")
	name := "admin/dist/img/ruby.514befa7.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistImgWordpressB08e20e3Svg reads file data from disk. It returns an error on failure.
func adminDistImgWordpressB08e20e3Svg() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/img/wordpress.b08e20e3.svg")
	name := "admin/dist/img/wordpress.b08e20e3.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistIndexHtml reads file data from disk. It returns an error on failure.
func adminDistIndexHtml() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/index.html")
	name := "admin/dist/index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistJsAboutA232e5c8Js reads file data from disk. It returns an error on failure.
func adminDistJsAboutA232e5c8Js() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/js/about.a232e5c8.js")
	name := "admin/dist/js/about.a232e5c8.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistJsAboutA232e5c8JsMap reads file data from disk. It returns an error on failure.
func adminDistJsAboutA232e5c8JsMap() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/js/about.a232e5c8.js.map")
	name := "admin/dist/js/about.a232e5c8.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistJsAppDad71b3fJs reads file data from disk. It returns an error on failure.
func adminDistJsAppDad71b3fJs() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/js/app.dad71b3f.js")
	name := "admin/dist/js/app.dad71b3f.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistJsAppDad71b3fJsMap reads file data from disk. It returns an error on failure.
func adminDistJsAppDad71b3fJsMap() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/js/app.dad71b3f.js.map")
	name := "admin/dist/js/app.dad71b3f.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistJsChunkVendors2b6afee3Js reads file data from disk. It returns an error on failure.
func adminDistJsChunkVendors2b6afee3Js() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/js/chunk-vendors.2b6afee3.js")
	name := "admin/dist/js/chunk-vendors.2b6afee3.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistJsChunkVendors2b6afee3JsMap reads file data from disk. It returns an error on failure.
func adminDistJsChunkVendors2b6afee3JsMap() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/js/chunk-vendors.2b6afee3.js.map")
	name := "admin/dist/js/chunk-vendors.2b6afee3.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistJsPreferencesA0df0240Js reads file data from disk. It returns an error on failure.
func adminDistJsPreferencesA0df0240Js() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/js/preferences.a0df0240.js")
	name := "admin/dist/js/preferences.a0df0240.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistJsPreferencesA0df0240JsMap reads file data from disk. It returns an error on failure.
func adminDistJsPreferencesA0df0240JsMap() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/js/preferences.a0df0240.js.map")
	name := "admin/dist/js/preferences.a0df0240.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistJsProjects9c388682Js reads file data from disk. It returns an error on failure.
func adminDistJsProjects9c388682Js() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/js/projects.9c388682.js")
	name := "admin/dist/js/projects.9c388682.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistJsProjects9c388682JsMap reads file data from disk. It returns an error on failure.
func adminDistJsProjects9c388682JsMap() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/js/projects.9c388682.js.map")
	name := "admin/dist/js/projects.9c388682.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistJsProjectstack3ef56350Js reads file data from disk. It returns an error on failure.
func adminDistJsProjectstack3ef56350Js() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/js/projectstack.3ef56350.js")
	name := "admin/dist/js/projectstack.3ef56350.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistJsProjectstack3ef56350JsMap reads file data from disk. It returns an error on failure.
func adminDistJsProjectstack3ef56350JsMap() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/js/projectstack.3ef56350.js.map")
	name := "admin/dist/js/projectstack.3ef56350.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistManifestJson reads file data from disk. It returns an error on failure.
func adminDistManifestJson() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/manifest.json")
	name := "admin/dist/manifest.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// adminDistRobotsTxt reads file data from disk. It returns an error on failure.
func adminDistRobotsTxt() (*asset, error) {
	path := filepath.Join(rootDir, "admin/dist/robots.txt")
	name := "admin/dist/robots.txt"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"admin/dist/css/app.78060d66.css": adminDistCssApp78060d66Css,
	"admin/dist/css/chunk-vendors.19588e8d.css": adminDistCssChunkVendors19588e8dCss,
	"admin/dist/css/preferences.11cfcf84.css": adminDistCssPreferences11cfcf84Css,
	"admin/dist/css/projects.6e0ed6ad.css": adminDistCssProjects6e0ed6adCss,
	"admin/dist/css/projectstack.32e9bd3e.css": adminDistCssProjectstack32e9bd3eCss,
	"admin/dist/favicon.ico": adminDistFaviconIco,
	"admin/dist/gears.json": adminDistGearsJson,
	"admin/dist/img/angular.e224f5ed.svg": adminDistImgAngularE224f5edSvg,
	"admin/dist/img/apache.12c49354.svg": adminDistImgApache12c49354Svg,
	"admin/dist/img/codeigniter.434bf735.svg": adminDistImgCodeigniter434bf735Svg,
	"admin/dist/img/django.28fe09a0.svg": adminDistImgDjango28fe09a0Svg,
	"admin/dist/img/drupal.66089b06.svg": adminDistImgDrupal66089b06Svg,
	"admin/dist/img/elasticsearch.3ecfa530.svg": adminDistImgElasticsearch3ecfa530Svg,
	"admin/dist/img/flask.318d58cb.svg": adminDistImgFlask318d58cbSvg,
	"admin/dist/img/icons/android-chrome-192x192.png": adminDistImgIconsAndroidChrome192x192Png,
	"admin/dist/img/icons/android-chrome-512x512.png": adminDistImgIconsAndroidChrome512x512Png,
	"admin/dist/img/icons/apple-touch-icon-120x120.png": adminDistImgIconsAppleTouchIcon120x120Png,
	"admin/dist/img/icons/apple-touch-icon-152x152.png": adminDistImgIconsAppleTouchIcon152x152Png,
	"admin/dist/img/icons/apple-touch-icon-180x180.png": adminDistImgIconsAppleTouchIcon180x180Png,
	"admin/dist/img/icons/apple-touch-icon-60x60.png": adminDistImgIconsAppleTouchIcon60x60Png,
	"admin/dist/img/icons/apple-touch-icon-76x76.png": adminDistImgIconsAppleTouchIcon76x76Png,
	"admin/dist/img/icons/apple-touch-icon.png": adminDistImgIconsAppleTouchIconPng,
	"admin/dist/img/icons/favicon-16x16.png": adminDistImgIconsFavicon16x16Png,
	"admin/dist/img/icons/favicon-32x32.png": adminDistImgIconsFavicon32x32Png,
	"admin/dist/img/icons/msapplication-icon-144x144.png": adminDistImgIconsMsapplicationIcon144x144Png,
	"admin/dist/img/icons/mstile-150x150.png": adminDistImgIconsMstile150x150Png,
	"admin/dist/img/icons/safari-pinned-tab.svg": adminDistImgIconsSafariPinnedTabSvg,
	"admin/dist/img/joomla.d8aa2e45.svg": adminDistImgJoomlaD8aa2e45Svg,
	"admin/dist/img/laravel.1766a461.svg": adminDistImgLaravel1766a461Svg,
	"admin/dist/img/logo.63a7d78d.svg": adminDistImgLogo63a7d78dSvg,
	"admin/dist/img/mariadb.e16110bc.svg": adminDistImgMariadbE16110bcSvg,
	"admin/dist/img/memcached.2bcccabf.svg": adminDistImgMemcached2bcccabfSvg,
	"admin/dist/img/mysql.dd2a5a35.svg": adminDistImgMysqlDd2a5a35Svg,
	"admin/dist/img/nginx.eae76401.svg": adminDistImgNginxEae76401Svg,
	"admin/dist/img/nodejs.94cafb0d.svg": adminDistImgNodejs94cafb0dSvg,
	"admin/dist/img/perl.a025edb4.svg": adminDistImgPerlA025edb4Svg,
	"admin/dist/img/php.fa78b345.svg": adminDistImgPhpFa78b345Svg,
	"admin/dist/img/python.51c2eab2.svg": adminDistImgPython51c2eab2Svg,
	"admin/dist/img/rails.2db29782.svg": adminDistImgRails2db29782Svg,
	"admin/dist/img/react.9a28da9f.svg": adminDistImgReact9a28da9fSvg,
	"admin/dist/img/redis.3c39fafe.svg": adminDistImgRedis3c39fafeSvg,
	"admin/dist/img/ruby.514befa7.svg": adminDistImgRuby514befa7Svg,
	"admin/dist/img/wordpress.b08e20e3.svg": adminDistImgWordpressB08e20e3Svg,
	"admin/dist/index.html": adminDistIndexHtml,
	"admin/dist/js/about.a232e5c8.js": adminDistJsAboutA232e5c8Js,
	"admin/dist/js/about.a232e5c8.js.map": adminDistJsAboutA232e5c8JsMap,
	"admin/dist/js/app.dad71b3f.js": adminDistJsAppDad71b3fJs,
	"admin/dist/js/app.dad71b3f.js.map": adminDistJsAppDad71b3fJsMap,
	"admin/dist/js/chunk-vendors.2b6afee3.js": adminDistJsChunkVendors2b6afee3Js,
	"admin/dist/js/chunk-vendors.2b6afee3.js.map": adminDistJsChunkVendors2b6afee3JsMap,
	"admin/dist/js/preferences.a0df0240.js": adminDistJsPreferencesA0df0240Js,
	"admin/dist/js/preferences.a0df0240.js.map": adminDistJsPreferencesA0df0240JsMap,
	"admin/dist/js/projects.9c388682.js": adminDistJsProjects9c388682Js,
	"admin/dist/js/projects.9c388682.js.map": adminDistJsProjects9c388682JsMap,
	"admin/dist/js/projectstack.3ef56350.js": adminDistJsProjectstack3ef56350Js,
	"admin/dist/js/projectstack.3ef56350.js.map": adminDistJsProjectstack3ef56350JsMap,
	"admin/dist/manifest.json": adminDistManifestJson,
	"admin/dist/robots.txt": adminDistRobotsTxt,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"admin": &bintree{nil, map[string]*bintree{
		"dist": &bintree{nil, map[string]*bintree{
			"css": &bintree{nil, map[string]*bintree{
				"app.78060d66.css": &bintree{adminDistCssApp78060d66Css, map[string]*bintree{}},
				"chunk-vendors.19588e8d.css": &bintree{adminDistCssChunkVendors19588e8dCss, map[string]*bintree{}},
				"preferences.11cfcf84.css": &bintree{adminDistCssPreferences11cfcf84Css, map[string]*bintree{}},
				"projects.6e0ed6ad.css": &bintree{adminDistCssProjects6e0ed6adCss, map[string]*bintree{}},
				"projectstack.32e9bd3e.css": &bintree{adminDistCssProjectstack32e9bd3eCss, map[string]*bintree{}},
			}},
			"favicon.ico": &bintree{adminDistFaviconIco, map[string]*bintree{}},
			"gears.json": &bintree{adminDistGearsJson, map[string]*bintree{}},
			"img": &bintree{nil, map[string]*bintree{
				"angular.e224f5ed.svg": &bintree{adminDistImgAngularE224f5edSvg, map[string]*bintree{}},
				"apache.12c49354.svg": &bintree{adminDistImgApache12c49354Svg, map[string]*bintree{}},
				"codeigniter.434bf735.svg": &bintree{adminDistImgCodeigniter434bf735Svg, map[string]*bintree{}},
				"django.28fe09a0.svg": &bintree{adminDistImgDjango28fe09a0Svg, map[string]*bintree{}},
				"drupal.66089b06.svg": &bintree{adminDistImgDrupal66089b06Svg, map[string]*bintree{}},
				"elasticsearch.3ecfa530.svg": &bintree{adminDistImgElasticsearch3ecfa530Svg, map[string]*bintree{}},
				"flask.318d58cb.svg": &bintree{adminDistImgFlask318d58cbSvg, map[string]*bintree{}},
				"icons": &bintree{nil, map[string]*bintree{
					"android-chrome-192x192.png": &bintree{adminDistImgIconsAndroidChrome192x192Png, map[string]*bintree{}},
					"android-chrome-512x512.png": &bintree{adminDistImgIconsAndroidChrome512x512Png, map[string]*bintree{}},
					"apple-touch-icon-120x120.png": &bintree{adminDistImgIconsAppleTouchIcon120x120Png, map[string]*bintree{}},
					"apple-touch-icon-152x152.png": &bintree{adminDistImgIconsAppleTouchIcon152x152Png, map[string]*bintree{}},
					"apple-touch-icon-180x180.png": &bintree{adminDistImgIconsAppleTouchIcon180x180Png, map[string]*bintree{}},
					"apple-touch-icon-60x60.png": &bintree{adminDistImgIconsAppleTouchIcon60x60Png, map[string]*bintree{}},
					"apple-touch-icon-76x76.png": &bintree{adminDistImgIconsAppleTouchIcon76x76Png, map[string]*bintree{}},
					"apple-touch-icon.png": &bintree{adminDistImgIconsAppleTouchIconPng, map[string]*bintree{}},
					"favicon-16x16.png": &bintree{adminDistImgIconsFavicon16x16Png, map[string]*bintree{}},
					"favicon-32x32.png": &bintree{adminDistImgIconsFavicon32x32Png, map[string]*bintree{}},
					"msapplication-icon-144x144.png": &bintree{adminDistImgIconsMsapplicationIcon144x144Png, map[string]*bintree{}},
					"mstile-150x150.png": &bintree{adminDistImgIconsMstile150x150Png, map[string]*bintree{}},
					"safari-pinned-tab.svg": &bintree{adminDistImgIconsSafariPinnedTabSvg, map[string]*bintree{}},
				}},
				"joomla.d8aa2e45.svg": &bintree{adminDistImgJoomlaD8aa2e45Svg, map[string]*bintree{}},
				"laravel.1766a461.svg": &bintree{adminDistImgLaravel1766a461Svg, map[string]*bintree{}},
				"logo.63a7d78d.svg": &bintree{adminDistImgLogo63a7d78dSvg, map[string]*bintree{}},
				"mariadb.e16110bc.svg": &bintree{adminDistImgMariadbE16110bcSvg, map[string]*bintree{}},
				"memcached.2bcccabf.svg": &bintree{adminDistImgMemcached2bcccabfSvg, map[string]*bintree{}},
				"mysql.dd2a5a35.svg": &bintree{adminDistImgMysqlDd2a5a35Svg, map[string]*bintree{}},
				"nginx.eae76401.svg": &bintree{adminDistImgNginxEae76401Svg, map[string]*bintree{}},
				"nodejs.94cafb0d.svg": &bintree{adminDistImgNodejs94cafb0dSvg, map[string]*bintree{}},
				"perl.a025edb4.svg": &bintree{adminDistImgPerlA025edb4Svg, map[string]*bintree{}},
				"php.fa78b345.svg": &bintree{adminDistImgPhpFa78b345Svg, map[string]*bintree{}},
				"python.51c2eab2.svg": &bintree{adminDistImgPython51c2eab2Svg, map[string]*bintree{}},
				"rails.2db29782.svg": &bintree{adminDistImgRails2db29782Svg, map[string]*bintree{}},
				"react.9a28da9f.svg": &bintree{adminDistImgReact9a28da9fSvg, map[string]*bintree{}},
				"redis.3c39fafe.svg": &bintree{adminDistImgRedis3c39fafeSvg, map[string]*bintree{}},
				"ruby.514befa7.svg": &bintree{adminDistImgRuby514befa7Svg, map[string]*bintree{}},
				"wordpress.b08e20e3.svg": &bintree{adminDistImgWordpressB08e20e3Svg, map[string]*bintree{}},
			}},
			"index.html": &bintree{adminDistIndexHtml, map[string]*bintree{}},
			"js": &bintree{nil, map[string]*bintree{
				"about.a232e5c8.js": &bintree{adminDistJsAboutA232e5c8Js, map[string]*bintree{}},
				"about.a232e5c8.js.map": &bintree{adminDistJsAboutA232e5c8JsMap, map[string]*bintree{}},
				"app.dad71b3f.js": &bintree{adminDistJsAppDad71b3fJs, map[string]*bintree{}},
				"app.dad71b3f.js.map": &bintree{adminDistJsAppDad71b3fJsMap, map[string]*bintree{}},
				"chunk-vendors.2b6afee3.js": &bintree{adminDistJsChunkVendors2b6afee3Js, map[string]*bintree{}},
				"chunk-vendors.2b6afee3.js.map": &bintree{adminDistJsChunkVendors2b6afee3JsMap, map[string]*bintree{}},
				"preferences.a0df0240.js": &bintree{adminDistJsPreferencesA0df0240Js, map[string]*bintree{}},
				"preferences.a0df0240.js.map": &bintree{adminDistJsPreferencesA0df0240JsMap, map[string]*bintree{}},
				"projects.9c388682.js": &bintree{adminDistJsProjects9c388682Js, map[string]*bintree{}},
				"projects.9c388682.js.map": &bintree{adminDistJsProjects9c388682JsMap, map[string]*bintree{}},
				"projectstack.3ef56350.js": &bintree{adminDistJsProjectstack3ef56350Js, map[string]*bintree{}},
				"projectstack.3ef56350.js.map": &bintree{adminDistJsProjectstack3ef56350JsMap, map[string]*bintree{}},
			}},
			"manifest.json": &bintree{adminDistManifestJson, map[string]*bintree{}},
			"robots.txt": &bintree{adminDistRobotsTxt, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

